"""initial schema

Revision ID: e76642326a7c
Revises: 
Create Date: 2026-05-28 10:41:27.641424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76642326a7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('document', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_closings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('marketplace', sa.String(length=40), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discounts_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('marketplace_fees_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('invoices_pending', sa.Integer(), nullable=False),
    sa.Column('invoices_authorized', sa.Integer(), nullable=False),
    sa.Column('invoices_rejected', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'marketplace', name='uq_daily_closing_date_marketplace')
    )
    with op.batch_alter_table('daily_closings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_closings_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_closings_marketplace'), ['marketplace'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('marketplace_sku', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ean', sa.String(length=40), nullable=True),
    sa.Column('ncm', sa.String(length=20), nullable=True),
    sa.Column('cfop', sa.String(length=20), nullable=True),
    sa.Column('cest', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=True),
    sa.Column('cst', sa.String(length=10), nullable=True),
    sa.Column('csosn', sa.String(length=10), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=160), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('complement', sa.String(length=120), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_buyer_id'), ['buyer_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('marketplace_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=40), nullable=False),
    sa.Column('marketplace_order_id', sa.String(length=80), nullable=False),
    sa.Column('order_datetime', sa.DateTime(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('marketplace_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_status', sa.String(length=40), nullable=False),
    sa.Column('fiscal_status', sa.String(length=60), nullable=False),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_orders_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_fiscal_status'), ['fiscal_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_marketplace'), ['marketplace'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_marketplace_order_id'), ['marketplace_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_order_datetime'), ['order_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_order_status'), ['order_status'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=True),
    sa.Column('invoice_series', sa.String(length=20), nullable=True),
    sa.Column('access_key', sa.String(length=80), nullable=True),
    sa.Column('xml_path', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ncm', sa.String(length=20), nullable=True),
    sa.Column('cfop', sa.String(length=20), nullable=True),
    sa.Column('cest', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)

    op.create_table('invoice_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_events_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_events_invoice_id'))

    op.drop_table('invoice_events')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_order_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('marketplace_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_order_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_order_datetime'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_marketplace_order_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_marketplace'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_fiscal_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_buyer_id'))

    op.drop_table('marketplace_orders')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_buyer_id'))

    op.drop_table('addresses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))

    op.drop_table('products')
    with op.batch_alter_table('daily_closings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_closings_marketplace'))
        batch_op.drop_index(batch_op.f('ix_daily_closings_date'))

    op.drop_table('daily_closings')
    op.drop_table('buyers')
    # ### end Alembic commands ###
